#!/bin/sh

if [ -z "$1" ]; then
    echo "usage: $0 datpath" 1>&2
    exit 1
else
    DATPATH=$1
fi

set -C
set -e
#DATPATH=$HOME/.web/$DATPATH

DATPATH=`datpath $DATPATH`
PAT="(jpg|jpeg|gif|png|zip|lzh|mpg|bmp)$"

zgu $DATPATH | grep ^http | egrep -i $PAT > IMG
zgu $DATPATH | grep ^http | egrep -iv $PAT | zgu -h > DOC.html
