#!/usr/bin/python
import os.path
import shutil
import sys

for f in sys.argv[1:]:
    src = os.path.abspath(f)
    dir = os.path.dirname(src)
    base = os.path.basename(src)
    parent = os.path.basename(dir)
    dst = os.path.join(dir, parent + '_' + base)
    if os.path.exists(dst):
        print >> sys.stderr, '%s: exists' % dst
        continue
    print '%s -> %s' % (src, dst)
    shutil.move(src, dst)
