#!/usr/bin/python
# -*- coding: utf-8 -*-
# 2007-02-04現在、Amazonのモバイルでaltの位置がおかしいから調整する。
import re
import sys


def _main():
    buf = sys.stdin.read()
    found = re.search(r'( alt="[^"]+?")', buf)
    if not found:
        return
    alt = found.group(1)

    buf = buf[:found.start()] + buf[found.end():]
    buf = re.sub(r' alt=""', alt, buf)

    buf = buf.replace('&', '&amp;')
    sys.stdout.write(buf)

_main()
