#!/bin/sh -e
ID=104787602969620799839

alias	mget='wget -q --random-wait --header="Accept-Encoding: gzip, compres, bzip, bzip2, deflate" --header="Accept-Language: ja; q=1.0, en;q=0.5" -U "Buzz-Reader/2010-02-13" -w 2'

cd "$HOME/backup/buzz" || exit 1
DATE=`date +%Y-%m-%d -d yesterday`

mget -O $DATE.xml --ca-directory=$HOME/.certs \
    "http://www.googleapis.com/buzz/v1/activities/$ID/@public?alt=atom&max-results=100"
bzip2 -f $DATE.xml
