#!/bin/sh

LOG_DIR=/var/local/log/saku
DATE=`date +%Y-%m-%d`

if [ -n "$1" ]; then
	LOG="$LOG_DIR/$1"
else
	LOG="$LOG_DIR/$DATE"
fi

awk -v FS="<>" "(NF > 4) && (\$6 ~ /shinGETsu/) {print \$2\" \"\$6}" $LOG | sort -u
