#!/bin/bash -xe
case $(git branch) in
    *development* ) git checkout development ;;
    *master* )      git checkout master ;;
    * )             git checkout main ;;
esac

git pull --prune
git fetch --prune origin
