#!/usr/bin/python
#
# Copyright (c) 2012 Satoshi Fukutomi <info@fuktommy.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

import os.path
import subprocess

target = [
    ('~/bin/.git', 'home-bin'),
    ('~/devel/saku/.git', 'saku-ex'),
    ('~/devel/saku-trunk/.git', 'saku-trunk'),
    ('~/fuk/backup/sakura/srv/git/genpasswd-android/.git', 'genpasswd'),
    ('~/fuk/backup/sakura/srv/sysconfig/.git', 'sysconfig'),
    ('~/fuk/backup/sakura/srv/stage/blogch3/.git', 'blogch3'),
    ('~/fuk/backup/sakura/srv/stage/fuktommy/.git', 'fuktommy.com'),
    ('~/fuk/backup/sakura/srv/stage/shingetsu/.git', 'shingetsu.info'),
]

backup_dir = '~/fuk/gdrive/git'

rsync = ['rsync', '--delete', '--delete-excluded', '-avh']


def do_backup(src, dst):
    src_path = os.path.expanduser(src)
    dst_path = os.path.join(os.path.expanduser(backup_dir),
                            os.path.expanduser(dst))
    print 'copying', src, 'to', dst, '...'
    command = rsync + [src_path + '/', dst_path + '/']
    subprocess.Popen(command).wait()


for src, dst in target:
    do_backup(src, dst)
