#!/bin/sh

IVIEW="/cygdrive/c/Program Files/IrfanView/i_view32.exe"
TARGET="$1"
if echo $TARGET | grep "\.txt$" > /dev/null; then
    SS=1
elif [ -z "$TARGET" ]; then
    TARGET=.
fi
TARGET=`cygpath -a -w $TARGET`
if [ -n "$SS" ]; then
    TARGET="/slideshow=$TARGET"
fi
setsid "$IVIEW" $TARGET &
