#!/bin/sh -e

IVIEW="/cygdrive/c/Program Files (x86)/IrfanView/i_view32.exe"
TARGET="$1"

case $TARGET in
    *.txt)
        ARG=/slideshow=$TARGET
    ;;
    ?*)
        cd $TARGET/.
        ARG=.\\
    ;;
    *)
        ARG=.\\
    ;;
esac

setsid "$IVIEW" $ARG &
