#!/bin/sh
rsync -ahv \
    --exclude="- /Android/data/" \
    --exclude="- /Comica/" \
    --exclude="- /Evernote/" \
    --exclude="- /DCIM/.thumbnails/" \
    --exclude="- /anchan/" \
    --exclude="- /data/jp.twitbeam/" \
    --exclude="- /external_sd/" \
    --exclude="- /newsrob/" \
    --exclude="- /svox/" \
    --exclude="- /videos/" \
    --exclude="- /Color 1280x720.mp4" \
    /cygdrive/f/ $HOME/fuk/backup/android/

#rsync -ahv \
#    --exclude="- /Android/data/" \
#    --exclude="- /DCIM/.thumbnails/" \
#    --exclude="- /newsrob/" \
#    /cygdrive/e/ $HOME/fuk/backup/android_sd/
