#!/usr/bin/python3
import base64
import hashlib
import sys

if len(sys.argv) != 2:
    sys.exit("Usage: mkpasswd seedfile")
else:
    filename = sys.argv[1]

f = open(filename, 'rb')
buf = f.read()
f.close()
digest = hashlib.md5(buf).digest()
passwd = base64.b64encode(digest).decode('ascii').replace("=", "")
print(passwd)
