#!/bin/sh -e
SUFFIX=$1
if [ -z "$SUFFIX" ]; then
    echo "usage: mkwinsaku suffix" 1>&2
    exit 1
fi
BASENAME="winsaku${SUFFIX}"
/cygdrive/c/Python27/python setup-win.py py2exe
sleep 1
rm -R dist/tcl/tcl*/tzdata
rm -R dist/tcl/tk*/{images,demos,msgs}
mv dist ../$BASENAME
cd ..
zip -v -r -9 $BASENAME.zip $BASENAME
