#!/usr/bin/python
#
"""Orderd Wget.

usage: owget -p "%03d.jpg" [url-list-files]
"""
#
# Copyright (c) 2012 Satoshi Fukutomi <info@fuktommy.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

import fileinput
import optparse
import os
import sys
import time

wget = ['wget', '-nv', '-T', '60', '-t', '2',
    '--header=Accept-Language: ja; q=1.0, en;q=0.5',
    '-U', 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)']


def parse_args(argv):
    usage = 'usage: %prog [options] [file...]'
    parser = optparse.OptionParser(usage=usage)
    parser.add_option('-p', '--output-pattern', dest='out_pattern',
                      default='%d',
                      help='output filename pattern')
    return parser.parse_args(argv)


def main():
    options, files = parse_args(sys.argv[1:])

    counter = 0
    for line in fileinput.input(files):
        url = line.strip()
        output = options.out_pattern % counter
        counter += 1
        os.spawnvp(os.P_WAIT,
                   wget[0],
                   wget + [url, '-O', output]);
        time.sleep(2)

if __name__ == '__main__':
    main()
