#!/usr/bin/python
import sys
from os import spawnlp, P_WAIT

if len(sys.argv) > 1:
    for url in sys.argv[1:]:
        url = url.replace('bbs.shingetsu.info', 'localhost:8000', 1)
        spawnlp(P_WAIT, 'w3m', 'w3m', url)
else:
    url = 'http://localhost:8000/'
    spawnlp(P_WAIT, 'w3m', 'w3m', url)
