#!/bin/sh

REMOTEARC="sakura.tar"
LOCALDIR="$HOME/backup"

cd $HOME
ssh sakura.fuktommy.com "tar -C /home -cvf - fuktommy" > "$LOCALDIR/$REMOTEARC"
chmod 600 "$LOCALDIR/$REMOTEARC"

rsync --delete -avh sakura.fuktommy.com:/srv/ /var/backup/sakura/srv/
