#!/bin/sh -e
#
# Subversion Wrapper
#
# $Id$
#
SVN=/usr/bin/svn

first="$1"
shift

case "$first" in
    st|status|up|update|ci|commit)
        $SVN info "$@" | awk '/^URL:/{print $2}'
esac

$SVN "$first" "$@"
