#!/usr/bin/perl -w

$dir  = "$ENV{HOME}/.web";
$file = "$dir/title.txt";

open PIPE, "|-", "/usr/bin/nkf -Se" or die;
@title = ();
open IN, $file or die;
while (<IN>) {
	@_ = split /\s+|<>/, $_, 2;
        $filename = $_[0];
        $filename =~ s|http://||;
	if (-f "$dir/$filename") {
		push @title, $_ if (-f "$dir/$filename");
	} else {
		print PIPE $_[1];
	}
}
close IN;
close PIPE;

open OUT, ">", $file or die;
foreach (@title) {
	print OUT;
}
close OUT;
