#!/usr/bin/python3
import urllib.parse
import sys
import fileinput

if len(sys.argv) > 1:
    print(urllib.parse.quote(sys.argv[1]))
else:
    f = fileinput.input()
    buf = []
    for line in f:
        buf.append(line)
    print(urllib.parse.quote("".join(buf)))
