#!/usr/bin/python
import urllib
import sys
import fileinput

if len(sys.argv) > 1:
    print urllib.quote(sys.argv[1])
else:
    f = fileinput.input()
    buf = []
    for line in f:
        buf.append(line)
    print urllib.quote("".join(buf))
