#!/bin/sh -e
DIR=$HOME/fuk/weblog

if [ -z "$1" ]; then
    echo "usage: weblog hostname [options]" 1>&2
    exit 1
fi

mv -vf $DIR/*.{png,html,log} $HOME/Trash/. || true

cat /var/log/httpd/$1.access.log "`ls /var/log/httpd/$1.access.log*|tail -1`" > $DIR/tmp.log
webalizer -o $DIR \
    -D $DIR/dnscache.bdb \
    -r fuktommy.com -r shingetsu.info \
    -v -i -n $* \
    $DIR/tmp.log

exec w3m $DIR/usage_*.html
